feat: update headers
VirtoCommerce/vc-theme-b2b-vue pull request #1009
Opened 2024-03-13 07:50 UTC by goldenmaya

## Description

## References
### Jira-link:

https://virtocommerce.atlassian.net/browse/VCST-606
### Artifact URL:

2024-03-19 08:34 UTC, asvishnyakov requested changes

2024-03-19 08:34 UTC, asvishnyakov commented on client-app/ui-kit/components/atoms/typography/vc-typography.vue
>  });
I'm not sure this is good for extensibility, May be it's better to do it in styles instead?

2024-03-19 08:36 UTC, asvishnyakov commented on client-app/ui-kit/components/atoms/typography/vc-typography.types.d.ts
> +export {};
You was needed to add `export {}` to tell Typescript it's a module, if there is not `import`

2024-03-22 04:19 UTC, goldenmaya commented on client-app/shared/catalog/components/category.vue
> +          <VcTypography tag="h1">
there is normal-case there

2024-03-27 03:14 UTC, asvishnyakov commented on client-app/assets/styles/main.scss
>    }
I found that there is difference in classes on body in `liquid`, used for production (environments) and `index.html`, used for local development (and storefront-less configuration in future). `font-lato` is missed on first:
https://github.com/VirtoCommerce/vc-theme-b2b-vue/blob/ec59c90530c6dbf5340478c70d371b3bd5c8fe4d/layout/theme.liquid#L9
https://github.com/VirtoCommerce/vc-theme-b2b-vue/blob/ec59c90530c6dbf5340478c70d371b3bd5c8fe4d/index.html#L16
I wanted to make PR and bring it into `index.html`, but than found you did this change and now I propose to remove it from `liquid` in this PR instead.

2024-03-27 03:39 UTC, asvishnyakov approved these changes

2024-03-28 03:01 UTC, merged