feat: push notifications archive/history
VirtoCommerce/vc-theme-b2b-vue pull request #1039
Opened 2024-04-02 15:11 UTC by NaMax66

## Description
https://virtocommerce.atlassian.net/browse/VCST-830

## References
### Jira-link:

### Artifact URL:

2024-04-11 05:45 UTC, goldenmaya requested changes

2024-04-11 05:45 UTC, goldenmaya commented on client-app/public/static/images/dashboard/icons/bell.svg
we already have the bell icon

2024-04-11 05:45 UTC, goldenmaya commented on client-app/shared/account/components/account-navigation-link.vue
> +  mask: url(/static/images/dashboard/icons/bell.svg) no-repeat center / contain;
Use basic bell icon, old icons will be removed.

2024-04-15 07:36 UTC, Andrew-Orlov approved these changes

2024-04-15 10:20 UTC, goldenmaya approved these changes

2024-04-19 10:05 UTC, merged