fix: add headers for file download;
VirtoCommerce/vc-theme-b2b-vue pull request #1042
Opened 2024-04-09 19:18 UTC by vkrashenko

## Description
The token is not passed when user downloading the file from quote
## References
### Jira-link:
https://virtocommerce.atlassian.net/browse/VCST-931
### Artifact URL:

2024-04-10 13:33 UTC, NaMax66 requested changes

2024-04-10 13:33 UTC, NaMax66 commented on client-app/shared/files/utils/index.ts
> +    const response = await fetch(fileUrl, {
use client-app/core/api/common/composables/useFetch.ts

there is interceptor inside which add the header

2024-04-10 13:33 UTC, NaMax66 commented on client-app/shared/files/utils/index.ts
> +export async function generateLinkAndDownloadFile(fileUrl: string, fileName: string) {
use function name downloadFile

2024-04-10 13:33 UTC, NaMax66 commented on client-app/ui-kit/components/molecules/file/vc-file.vue
> +        <span v-if="isAttachedFile(file) || isUploadedFile(file)" class="vc-file__link" @click="downloadFile(file)">
try to keep <a> for accessibility. Just @click.prevent should help

2024-04-11 12:48 UTC, Andrew-Orlov commented on client-app/shared/files/utils/index.ts
> +    console.error("Request error:", error);
We have Logger

2024-04-11 13:30 UTC, NaMax66 approved these changes

2024-04-11 14:13 UTC, merged