fix: order summary print styles
VirtoCommerce/vc-theme-b2b-vue pull request #1135
Opened 2024-06-04 15:17 UTC by ivan-kalachikov

## Description

## References
### Jira-link:
https://virtocommerce.atlassian.net/browse/VCST-1250
### Artifact URL:

2024-06-10 06:15 UTC, goldenmaya requested changes

2024-06-10 08:46 UTC, goldenmaya requested changes

2024-06-10 08:46 UTC, goldenmaya commented on client-app/assets/styles/print/molecules/vc-layout-with-right-sidebar.scss
>    @apply p-0;
@apply block p-0;

2024-06-10 09:01 UTC, ivan-kalachikov commented on client-app/assets/styles/print/molecules/vc-layout-with-right-sidebar.scss
>    @apply p-0;
oops, thank you!

2024-06-11 08:42 UTC, Andrew-Orlov approved these changes

2024-06-11 08:43 UTC, goldenmaya approved these changes

2024-06-17 05:05 UTC, merged