feat: implement variations table-view
VirtoCommerce/vc-theme-b2b-vue pull request #1146
Opened 2024-06-12 10:07 UTC by goldenmaya

## Description

## References
### Jira-link:

https://virtocommerce.atlassian.net/browse/VCST-1278
### Artifact URL:

2024-06-12 13:52 UTC, NaMax66 commented
@goldenmaya could you fix it?
![image](https://github.com/VirtoCommerce/vc-theme-b2b-vue/assets/19205780/6057094b-081c-450c-b402-6bf1651ae009)

2024-06-12 14:06 UTC, NaMax66 commented on client-app/shared/catalog/components/product/variations-table.vue
> +        name: prop!.name,
prop!.name -> props.name
prop!.label! -> prop.label

label could be props defaults

2024-06-13 06:16 UTC, ivan-kalachikov requested changes
Great job, just a few small things to improve

2024-06-13 06:16 UTC, ivan-kalachikov commented on client-app/ui-kit/components/atoms/product-title/vc-product-title.vue
> +      @apply line-clamp-1;
Just wonder if we can use v-bind here, instead of setting `--lines` class?

https://vuejs.org/api/sfc-css-features#v-bind-in-css

2024-06-14 10:34 UTC, ivan-kalachikov approved these changes

2024-06-14 12:09 UTC, NaMax66 approved these changes

2024-06-20 10:27 UTC, Andrew-Orlov approved these changes

2024-06-20 14:47 UTC, merged