fix: cart infinity loading
VirtoCommerce/vc-theme-b2b-vue pull request #1303
Opened 2024-09-16 07:55 UTC by ivan-kalachikov

## Description

## References
### Jira-link:
https://virtocommerce.atlassian.net/browse/VCST-1782
### Artifact URL:

2024-09-17 07:52 UTC, Andrew-Orlov approved these changes

2024-09-17 09:52 UTC, NaMax66 approved these changes

2024-09-18 10:44 UTC, NaMax66 requested changes

2024-09-18 10:44 UTC, NaMax66 commented on client-app/shared/layout/components/header/_internal/bottom-header.vue
> +const route = useRoute();
code duplication
make simple composable

2024-09-18 11:12 UTC, NaMax66 approved these changes

2024-09-18 13:19 UTC, merged