ST-1739, ST-1776: Rename buttons, remove redirect after profile update
VirtoCommerce/vc-theme-b2b-vue pull request #151
Opened 2022-05-23 09:54 UTC by ilyawzrd

Description:

--

QA-test: ST-1741

Demo-test: ST-1742

Download artifact URL:

2022-05-23 09:56 UTC, artmakarov approved these changes

2022-05-23 10:04 UTC, trueboroda requested changes

2022-05-23 10:04 UTC, trueboroda commented on locales/de.json
> +          "select_button": "Select"
Use link to common labels

2022-05-23 10:04 UTC, trueboroda commented on locales/en.json
> +          "select_button": "Select"
Use link to common labels

2022-05-24 07:19 UTC, trueboroda approved these changes

2022-05-24 07:20 UTC, merged