ST-2150 Show in stock products by default on category page
VirtoCommerce/vc-theme-b2b-vue pull request #182
Opened 2022-06-14 08:04 UTC by Andrew-Orlov

Description:

--

QA-test: ST-2153

Demo-test:

Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.5.0-pr-182-13cec857.zip

2022-06-14 10:42 UTC, trueboroda approved these changes

2022-06-16 15:29 UTC, Flanker72 commented on client-app/shared/catalog/composables/useProducts.ts
> +  const filters = shallowReactive<ProductsFilters>({ facets: [], inStock: true });
First uncheck doesn't trigger data refetch.

2022-06-22 09:48 UTC, trueboroda approved these changes

2022-06-22 12:47 UTC, artmakarov approved these changes

2022-06-29 11:07 UTC, Flanker72 approved these changes

2022-07-04 10:25 UTC, artmakarov requested changes

2022-07-04 10:25 UTC, artmakarov commented on client-app/pages/category.vue
> +  searchParams.value.filter = toFilterExpression(filters);
`searchParams` is a computed property. 
There should be no value assignment here.

2022-07-04 10:32 UTC, artmakarov commented on client-app/pages/category.vue
> +  searchParams.value.filter = toFilterExpression(filters);
This task may require a lot of refactoring

2022-07-13 12:29 UTC, trueboroda approved these changes

2022-07-14 06:21 UTC, Flanker72 approved these changes

2022-07-14 12:33 UTC, merged