feat(ST-1249): [Catalog] Implement Category/Subcategory selector
VirtoCommerce/vc-theme-b2b-vue pull request #194
Opened 2022-06-20 14:23 UTC by trueboroda

Description:

--

QA-test: ST-1252

Demo-test:

Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.3.0-pr-194-f0247f4b.zip

2022-06-21 10:07 UTC, goldenmaya commented
![Screenshot 2022-06-21 at 19 04 51](https://user-images.githubusercontent.com/16372194/174774687-a77607c8-aed2-4e26-a8a0-468ac9786e19.png)
![Screenshot 2022-06-21 at 18 56 56](https://user-images.githubusercontent.com/16372194/174774707-bfb45fd3-d461-42d0-8fee-b0f710fcd315.png)

Need to fix font-size && positioning

2022-06-21 10:09 UTC, goldenmaya requested changes
commented

2022-06-21 11:16 UTC, trueboroda commented
@goldenmaya  We don't make a pixel-perfect markup. We use a more appropriate tailwind class for design.  We plan to customize font sizes as it took place on a design as a separate task.

2022-06-21 14:07 UTC, Flanker72 approved these changes

2022-06-22 09:18 UTC, artmakarov approved these changes

2022-06-22 09:34 UTC, merged