ST-2417: Change menu item for compare products, fix badge position
VirtoCommerce/vc-theme-b2b-vue pull request #222
Opened 2022-07-05 07:23 UTC by ilyawzrd

Description:

--

QA-test: ST-2419

Demo-test:

Download artifact URL:

2022-07-05 07:26 UTC, trueboroda approved these changes

2022-07-07 09:04 UTC, Flanker72 commented on client-app/shared/layout/components/header/_internal/bottom-header.vue
> +                  class="absolute -top-[8px] !-right-[0.4rem] flex items-center h-5 rounded-xl bg-white border border-[color:var(--color-primary)] px-1.5 font-bold text-xs"
Why Checkout and Compare badges have different classes and different position logic?

2022-07-08 06:28 UTC, Flanker72 requested changes
Read the messages carefully. 

### Badge should be aligned to the top right from the icon box

What's unclear here?

2022-07-14 15:19 UTC, Flanker72 approved these changes

2022-07-21 04:41 UTC, merged