ST-2123 Keep show differences only checkbox state on delete product at compare products page
VirtoCommerce/vc-theme-b2b-vue pull request #224
Opened 2022-07-05 13:37 UTC by Andrew-Orlov

Description:

--

QA-test: ST-2125

Demo-test:

Download artifact URL:

2022-07-05 13:41 UTC, trueboroda requested changes

2022-07-05 13:41 UTC, trueboroda commented on client-app/pages/compare-products.vue
> +      console.log(uniqueValues);
remove cosole.log

2022-07-05 13:45 UTC, trueboroda approved these changes

2022-07-10 13:30 UTC, Flanker72 approved these changes

2022-07-13 14:49 UTC, merged