feat(ST-2270): Implement Send product to email
VirtoCommerce/vc-theme-b2b-vue pull request #239
Opened 2022-07-19 14:35 UTC by trueboroda

Description:

--

QA-test: ST-2273

Demo-test:

Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.5.0-pr-239-1c3fd2dd.zip

2022-07-19 14:45 UTC, Andrew-Orlov approved these changes

2022-07-19 19:47 UTC, Flanker72 requested changes
Please, read the task CAREFULLY. This code is not needed at all.

2022-07-20 14:23 UTC, Flanker72 commented on client-app/shared/catalog/components/product-price-block.vue
> +const mailToLink = computed(() => `mailto:?subject=${props.product?.name}&body=${pageUrl}`);
Product name should be escaped. Special chars like `&` or `+` are not handled properly.
Both subject and body should be wrapped in `encodeURIComponent` to accept any string.

2022-07-20 14:45 UTC, trueboroda commented on client-app/ui-kit/components/atoms/button/vc-button.vue
> +    :is="isExternalLink ? 'a' : isLink ? 'router-link' : 'button'"
router-link adds the current hostname to the address.

2022-07-20 16:47 UTC, Flanker72 approved these changes

2022-07-22 15:14 UTC, merged