feat(ST-563): branches-dialog desktop/mobile layout + desktop category func
VirtoCommerce/vc-theme-b2b-vue pull request #246
Opened 2022-07-28 05:02 UTC by goldenmaya

Description:

--

QA-test:

Demo-test:

Download artifact URL:

2022-07-29 07:26 UTC, artmakarov commented on client-app/shared/fulfillmentCenters/components/branches-dialog.vue
> +  () => JSON.stringify(selectedBranchesIdsTemp) === JSON.stringify(selectedBranchesIds.value)
selectedBranchesIdsTemp`.value`

2022-07-29 07:26 UTC, artmakarov commented on client-app/pages/category.vue
> +                  v-html="$t('pages.catalog.branch_availability_filter_card.available_in', { n: savedBranches.length })"
Maybe use `<i18n-t />`  instead of `v-html`
https://vue-i18n.intlify.dev/guide/advanced/component.html

2022-07-29 08:27 UTC, Andrew-Orlov commented on client-app/pages/category.vue
> +        availableInMobile.value = JSON.parse(localStorage.getItem(FFC_TEMP_LOCAL_STORAGE_NAME));
Use `useLocalStorage` from `vueuse` package

2022-07-29 08:42 UTC, trueboroda requested changes

2022-07-29 08:42 UTC, trueboroda commented on client-app/shared/fulfillmentCenters/components/branches-dialog.vue
> +const selectedBranchesIdsTemp = useLocalStorage<string[]>(FFC_TEMP_LOCAL_STORAGE_NAME, []);
don't use the temp localstorage value. Use event to pass result data. And operate result data in place.

2022-07-29 08:42 UTC, trueboroda commented on client-app/shared/catalog/types/search.ts
> +  availableIn?: string[];
it is not used now. but posible can be used.

2022-08-01 05:54 UTC, trueboroda approved these changes

2022-08-01 06:40 UTC, artmakarov commented on client-app/pages/category.vue
> +  if (isMobileSidebar) {
isMobileSidebar`.value`

2022-08-01 06:40 UTC, artmakarov commented on client-app/pages/category.vue
> +        if (isMobileSidebar) {
isMobileSidebar`.value`

2022-08-01 06:40 UTC, artmakarov commented on client-app/shared/catalog/components/products-filters.vue
> +  _filters.availableIn = props.filters.availableIn;
clone an array

2022-08-01 06:40 UTC, artmakarov commented on client-app/shared/catalog/components/products-filters.vue
> +    _filters.availableIn = newValue;
clone an array

2022-08-01 06:40 UTC, artmakarov commented on client-app/shared/fulfillmentCenters/components/branch-item.vue
> +    type: Object as PropType<any>,
preferably add the type

2022-08-01 06:40 UTC, artmakarov commented on client-app/shared/fulfillmentCenters/components/branch-item.vue
> +.closed {
Maybe `.branch-item .closed {`

2022-08-01 14:28 UTC, artmakarov approved these changes

2022-08-03 02:51 UTC, merged