feat(ST-2733): category page redesign
VirtoCommerce/vc-theme-b2b-vue pull request #257
Opened 2022-08-03 09:24 UTC by goldenmaya

Description:
https://virtocommerce.atlassian.net/browse/ST-2733

--

QA-test: ST-2736

Demo-test:

Download artifact URL:

2022-08-04 14:25 UTC, artmakarov approved these changes

2022-08-04 15:28 UTC, trueboroda requested changes

2022-08-04 15:28 UTC, trueboroda commented on client-app/shared/catalog/components/products-filters.vue
> +            <svg class="text-[color:var(--color-products-filter-button)]" height="12" width="12">
For what do we have some special color for the filters button? it should have or primary or secondary color. 
We don't want to make a Christmas tree out of our theme...

2022-08-04 15:28 UTC, trueboroda commented on client-app/shared/catalog/components/products-filters.vue
>      required: true,
remove required if it has a default option.

2022-08-05 08:20 UTC, goldenmaya commented on client-app/shared/catalog/components/products-filters.vue
> +            <svg class="text-[color:var(--color-products-filter-button)]" height="12" width="12">
Мы будем переходить на новую цветовую палитру, это один из оттенков, который будет представлен в основной палитре, чтобы когда будем встраивать палитру их потом можно было быстро найти мы создаем переменные. На счет "Christmas tree" должно обсуждаться с дизайнером (но в данном случае этот цвет выглядит намного лучше здесь, чем тот же primary-color).

2022-08-08 13:16 UTC, trueboroda approved these changes

2022-08-08 13:25 UTC, merged