feat: see more
VirtoCommerce/vc-theme-b2b-vue pull request #430
Opened 2023-01-29 21:22 UTC by vkrashenko

Description:
https://dev.azure.com/omnia-opus/OPUS/_workitems/edit/564/
https://www.figma.com/proto/BJLSDfvrUKkvMPqPLKOFXB/STOREFRONT?node-id=13804%3A93211&starting-point-node-id=13804%3A92937&show-proto-sidebar=1
--

QA-test:

Demo-test:

Download artifact URL:

2023-01-30 07:21 UTC, goldenmaya commented on client-app/shared/catalog/components/product/properties.vue
> +      class="my-0.5 !h-10 text-blue-600 dark:text-blue-500 underline hover:cursor-pointer decoration-dashed"
1. use --color-link and --color-link-hover variables
2. do not use !h-10

2023-01-30 07:21 UTC, goldenmaya commented on client-app/shared/catalog/components/product/properties.vue
> +    <a
I'm not sure but I think it should be placed after Vendor property.

2023-01-30 07:21 UTC, goldenmaya commented on client-app/shared/catalog/components/product/properties.vue
> +      <i class="md:hidden px-2 fas fa-save text-2xl" />
use `<VcIcon name="chevron-down" size="xs" />`

2023-01-30 11:45 UTC, muller39 commented on client-app/shared/catalog/components/product/properties.vue
> +      <VcIcon class="text-[color:var(--color-primary)]" :name="[showAll ? 'chevron-up' : 'chevron-down']" size="xs" />
chamge 'atributes' order
class="text-[color:var(--color-primary)]" :name="[showAll ? 'chevron-up' : 'chevron-down']" size="xs"
to
:name="[showAll ? 'chevron-up' : 'chevron-down']" size="xs" class="text-[color:var(--color-primary)]"

2023-01-30 11:49 UTC, muller39 commented on client-app/shared/catalog/components/product/properties.vue
> +        showAll == true ? $t("shared.catalog.product_details.see_less") : $t("shared.catalog.product_details.see_more")
'showAll' has boolean type, it coud be simply?
showAll ? $t("shared.catalog.product_details.see_less") : $t("shared.catalog.product_details.see_more")

2023-01-30 11:54 UTC, muller39 commented on client-app/shared/catalog/components/product/properties.vue
>  import { Product } from "@/xapi/types";
xapi inclide export * from "./types";

import { Product } from "@/xapi/types";
to
import { Product } from "@/xapi";

2023-01-30 11:57 UTC, muller39 commented on client-app/shared/catalog/components/product/properties.vue
>  const props = defineProps({
mb change 'const props = defineProps(...' to ower interface solution? [like here](https://github.com/VirtoCommerce/vc-theme-b2b-vue/pull/432/files#diff-bfd252f92c636f553a414b5b0033155be478d69dae522045afad8719879f23e5:~:text=%7D)%3B-,interface%20Props%20%7B,-cart%3A%20CartType)

2023-01-30 12:03 UTC, muller39 approved these changes

2023-01-31 11:29 UTC, artmakarov requested changes

2023-01-31 11:29 UTC, artmakarov commented on client-app/shared/catalog/components/product/properties.vue
> +      v-if="product.properties && product.properties.length > MAX_DISPLAY_ITEMS"
use `groupedProperties.length > MAX_DISPLAY_ITEMS`

2023-01-31 11:29 UTC, artmakarov commented on client-app/shared/catalog/components/product/properties.vue
> +      <VcIcon :name="[showAll ? 'chevron-up' : 'chevron-down']" size="xs" class="text-[color:var(--color-primary)]" />
`:name="showAll ? 'chevron-up' : 'chevron-down'`

2023-01-31 11:31 UTC, artmakarov commented on locales/en.json
> +        "see_less": "See less"
move to `common.buttons` section

2023-02-01 09:03 UTC, artmakarov approved these changes

2023-02-01 11:34 UTC, merged