PT-12829: move confirmEmail request to xapi
VirtoCommerce/vc-theme-b2b-vue pull request #663
Opened 2023-08-01 10:12 UTC by ksavosteev

Description:

--

QA-test:

Demo-test:

Download artifact URL:

2023-08-03 09:45 UTC, NaMax66 commented on client-app/pages/sign-up.vue
> +      component: RegistrationConfirmEmailDialog,
router.push({ name: "Welcome" })  after confirm

2023-08-08 10:50 UTC, asvishnyakov requested changes

2023-08-08 10:50 UTC, asvishnyakov commented on client-app/core/api/graphql/account/mutations/registerAccount/requestRegistration.graphql
> +      requireEmailVerification
Remove unused field

2023-08-08 10:50 UTC, asvishnyakov commented on client-app/core/api/graphql/account/mutations/confirmEmail/confirmEmail.graphql
> +    }
Remove unused fields

2023-08-08 11:56 UTC, ksavosteev commented on client-app/core/api/graphql/account/mutations/registerAccount/requestRegistration.graphql
> +      requireEmailVerification
May be used in the future

2023-08-08 11:56 UTC, ksavosteev commented on client-app/core/api/graphql/account/mutations/confirmEmail/confirmEmail.graphql
> +    }
May be used in the future

2023-08-09 08:36 UTC, Andrew-Orlov approved these changes

2023-08-09 09:13 UTC, asvishnyakov approved these changes

2023-08-09 09:13 UTC, merged