refactor: remove fontawesome
VirtoCommerce/vc-theme-b2b-vue pull request #700
Opened 2023-08-23 10:04 UTC by goldenmaya

Description:
https://virtocommerce.atlassian.net/browse/ST-4361

--

QA-test:

Demo-test:

Download artifact URL:

2023-08-24 09:51 UTC, NaMax66 commented on client-app/pages/forgot-password.vue
> +      <div v-if="!isSucceeded && false">
false?

2023-08-24 09:51 UTC, NaMax66 commented on client-app/shared/catalog/components/category-selector.vue
> +        class="-mx-1.5 flex grow items-center gap-1.5 rounded-sm px-1.5 py-0.5 hover:bg-[--color-neutral-50]"
Should we really use -mx?

2023-08-24 09:54 UTC, goldenmaya commented on client-app/shared/catalog/components/category-selector.vue
> +        class="-mx-1.5 flex grow items-center gap-1.5 rounded-sm px-1.5 py-0.5 hover:bg-[--color-neutral-50]"
возможно, не знаю, не стала пока трогать тут верстку.

2023-08-24 10:16 UTC, NaMax66 approved these changes

2023-08-24 10:17 UTC, asvishnyakov requested changes

2023-08-24 10:17 UTC, asvishnyakov commented on client-app/shared/catalog/components/vendor.vue
> +      <span class="text-xs font-black"> {{ vendor.rating?.value }} </span>/5 ({{ vendor.rating?.reviewCount }})
Don't remove non-breaking space or add no-wrap

2023-08-25 07:36 UTC, asvishnyakov approved these changes

2023-08-25 07:41 UTC, merged