feat(company-info): implement new settings dropdown design
VirtoCommerce/vc-theme-b2b-vue pull request #720
Opened 2023-08-31 06:10 UTC by goldenmaya

Description:
https://virtocommerce.atlassian.net/browse/ST-4661

--

QA-test:

Demo-test:

Download artifact URL:

2023-08-31 07:15 UTC, asvishnyakov requested changes

2023-08-31 07:15 UTC, asvishnyakov commented on client-app/pages/company/info.vue
>                    </VcActionDropdownMenu>
Reuse this code and don't forget about permissions checking

2023-08-31 07:23 UTC, asvishnyakov requested changes

2023-08-31 07:23 UTC, asvishnyakov commented on client-app/pages/company/info.vue
> -            :item-actions-builder="itemActionsBuilder"
Remove no longer used variable `itemActionsBuilder` from typescript

2023-08-31 07:23 UTC, asvishnyakov commented on tailwind.config.ts
> +import {deprecate} from "util";
You're using jsdoc `@deprecated` and don't need to import this node.js function

2023-09-12 07:32 UTC, asvishnyakov requested changes
That's definitely not that I mean when I asked for reused code. I simply mean you should create shared component for that VcActionDropDownMenu with it's items and then use it twice in code. I think refactoring of the VcActionDropDownMenu should be part of UI Kit work and it should be done in the other way, like https://vuetifyjs.com/en/components/menus/ so you can be able to use component-based approach to build the menu, instead of passing classes, event handlers and other stuff as props. So it should be a separate task with mitigation about UI kit first, especially because we have the same actions on other pages and also other component which using VcActionDropDownMenu

2023-09-12 10:17 UTC, NaMax66 approved these changes

2023-09-13 08:22 UTC, asvishnyakov requested changes

2023-09-13 08:22 UTC, asvishnyakov commented on client-app/ui-kit/components/atoms/action-dropdown-menu/vc-action-dropdown-menu.vue
> +<!-- @deprecated the component will be removed from ui-kit -->
https://github.com/VirtoCommerce/vc-theme-b2b-vue/blob/c31ea77061d7407bf6b1cb385c37c7a8c190061c/client-app/ui-kit/components/atoms/types.d.ts#L7
Put it here instead please

2023-09-18 06:58 UTC, asvishnyakov approved these changes

2023-09-18 09:35 UTC, merged