feat: add full screen image preview
VirtoCommerce/vc-theme-b2b-vue pull request #729
Opened 2023-09-05 21:50 UTC by muller39

Description:
https://virtocommerce.atlassian.net/jira/software/projects/ST/issues/ST-4951?jql=project%20%3D%20%22ST%22%20AND%20assignee%20%3D%20%225f8da9890b07fb006f187e77%22%20ORDER%20BY%20created%20DESC

--

QA-test:

Demo-test:

Download artifact URL:

2023-09-06 10:13 UTC, asvishnyakov requested changes

2023-09-06 10:13 UTC, asvishnyakov commented on client-app/ui-kit/components/molecules/image-gallery/vc-image-gallery.vue
> +        class="vc-image-gallery__main-image absolute top-0 h-full w-full cursor-zoom-in rounded-sm object-cover object-center data-[te-lightbox-disabled]:cursor-auto"
Don't mix BEM with style helpers, if you use BEM, then move all applied styles to class via `@apply`

2023-09-07 06:42 UTC, NaMax66 approved these changes

2023-09-07 07:15 UTC, asvishnyakov approved these changes

2023-09-07 07:53 UTC, merged