feat: implement vc-chip new design
VirtoCommerce/vc-theme-b2b-vue pull request #744
Opened 2023-09-14 07:09 UTC by goldenmaya

Description:
https://virtocommerce.atlassian.net/browse/ST-4884

--

QA-test:

Demo-test:

Download artifact URL:

2023-09-14 09:32 UTC, NaMax66 approved these changes

2023-09-18 07:04 UTC, asvishnyakov requested changes

2023-09-18 07:04 UTC, asvishnyakov commented on client-app/shared/account/components/order-status.vue
> +  <VcChip :variant="orderStatus?.variant" :color="orderStatus?.color || defaultColor" truncate rounded>
Please look at `IOrderStatus`, create and replace required typings. Also, the same statuses are used in quotes, what about them?

2023-09-18 12:34 UTC, asvishnyakov approved these changes

2023-09-19 02:42 UTC, merged