feat: implement new currency-selector design
VirtoCommerce/vc-theme-b2b-vue pull request #819
Opened 2023-10-18 10:52 UTC by goldenmaya

## Description
https://virtocommerce.atlassian.net/browse/ST-5043
## References
### QA-test:
### Jira-link:
### Artifact URL:

2023-10-20 08:10 UTC, asvishnyakov requested changes

2023-10-20 08:10 UTC, asvishnyakov commented on client-app/ui-kit/components/atoms/popover/vc-popover.vue
> +      @keyup="trigger === 'click' && toggle(!isShown)"
Why not just call open/close too?

2023-10-23 03:05 UTC, goldenmaya commented on client-app/shared/catalog/components/product-price-block.vue
it uses vc-popover

2023-10-23 04:21 UTC, goldenmaya commented on client-app/ui-kit/components/atoms/popover/vc-popover.vue
> +      @keyup="trigger === 'click' && toggle(!isShown)"
it has to toggle menu on click or keyup

2023-10-23 04:56 UTC, asvishnyakov commented on client-app/shared/catalog/components/product-price-block.vue
So VcPopover was refactored and you just moved title & closed buttom out of component

2023-10-23 05:01 UTC, asvishnyakov approved these changes

2023-10-25 03:20 UTC, merged