feat: update email parser
VirtoCommerce/vc-theme-b2b-vue pull request #862
Opened 2023-11-14 14:11 UTC by NaMax66

## Description

## References
### Jira-link:

### Artifact URL:

2023-11-17 06:13 UTC, asvishnyakov approved these changes

2023-11-17 06:35 UTC, Andrew-Orlov approved these changes

2023-11-17 18:02 UTC, vkrashenko requested changes

2023-11-17 18:02 UTC, vkrashenko commented on client-app/shared/company/components/invite-member-modal/invite-member-modal.vue
> +        (value) => parseEmails(value).every((el) => el.isValid),
missing type

2023-11-17 18:02 UTC, vkrashenko commented on client-app/shared/company/components/invite-member-modal/invite-member-modal.vue
> +          return emailAddresses.every((emailAddress) => emailAddress.value.length <= MAX_EMAIL_LENGTH);
missing type

2023-11-22 11:16 UTC, NaMax66 commented on client-app/shared/company/components/invite-member-modal/invite-member-modal.vue
> +        (value) => parseEmails(value).every((el) => el.isValid),
automatically evaluated by TS

2023-11-22 11:16 UTC, NaMax66 commented on client-app/shared/company/components/invite-member-modal/invite-member-modal.vue
> +          return emailAddresses.every((emailAddress) => emailAddress.value.length <= MAX_EMAIL_LENGTH);
automatically evaluated by TS

2023-11-22 11:20 UTC, vkrashenko approved these changes

2023-11-22 11:21 UTC, merged