refactor: change usePopup to useModal, rename all dialogs to modals
VirtoCommerce/vc-theme-b2b-vue pull request #928
Opened 2024-01-09 06:11 UTC by Andrew-Orlov

## Description

Change usePopup to useModal, rename all dialogs to modals

## References
### Jira-link:

https://virtocommerce.atlassian.net/browse/ST-5452

### Artifact URL:

2024-01-17 17:00 UTC, NaMax66 approved these changes

2024-01-18 08:23 UTC, asvishnyakov requested changes

2024-01-18 08:23 UTC, asvishnyakov commented on client-app/shared/builder-io/components/landing-page.vue
> +  console.log(canShowContent.value);
Remove console.log

2024-01-18 11:40 UTC, asvishnyakov approved these changes

2024-02-06 09:28 UTC, merged