VCST-327: [Addresses] Tag address as favorite
VirtoCommerce/vc-theme-b2b-vue pull request #964
Opened 2024-02-12 16:35 UTC by vkrashenko

## Description

## References
### Jira-link:
https://virtocommerce.atlassian.net/browse/VCST-434
### Artifact URL:

2024-02-13 03:38 UTC, goldenmaya requested changes

2024-02-13 03:38 UTC, goldenmaya commented on client-app/pages/company/info.vue
> +                  <VcTooltip class="ml-1 !block" placement="bottom-start" strategy="fixed">
"!block" for what?

2024-02-13 03:38 UTC, goldenmaya commented on client-app/pages/company/info.vue
> +                          'text-[--color-primary-500]': address.isFavorite,
Merge 'dev' branch => use "text-neutral-400", "text-primary" classes

2024-02-13 03:38 UTC, goldenmaya commented on client-app/pages/company/info.vue
> +                        class="w-44 rounded-sm px-3.5 py-1.5 text-11 font-light shadow-sm-x-y"
1. text-11, shadow-sm-x-y classes are deprecated (See tailwind.config.ts).
2. check mobile view - 320px - 375px (w-44 looks weird).

2024-02-13 12:01 UTC, asvishnyakov requested changes

2024-02-13 12:01 UTC, asvishnyakov commented on client-app/pages/company/info.vue
> +                        v-html-safe="
There is nothing to sanitize, so it's redudant

2024-02-13 15:52 UTC, vkrashenko commented on locales/en.json
> +        "remove_from_favorites": "Remove from favorite ",
<img width="486" alt="image" src="https://github.com/VirtoCommerce/vc-theme-b2b-vue/assets/29459286/bb45c485-99fc-4612-8c67-ec83d9208b49">

2024-02-14 04:01 UTC, goldenmaya commented
![Screenshot 2024-02-14 at 12 59 37](https://github.com/VirtoCommerce/vc-theme-b2b-vue/assets/16372194/5fb805f0-398f-4cd2-ab80-be04fe4adfb0)
It's imposible to check layout.

2024-02-14 04:28 UTC, goldenmaya commented on client-app/pages/company/info.vue
> +                    class="flex items-center"
Are these changes necessary?

2024-02-14 04:29 UTC, goldenmaya commented on client-app/pages/company/info.vue
> +                  <VcIcon
Add empty line between tags

2024-02-14 07:56 UTC, artem-dudarev commented on locales/en.json
> +        "remove_from_favorites": "Remove from favorite ",
Remove trailing space.
Change `favorite` to `favorites`

2024-02-14 15:16 UTC, asvishnyakov approved these changes

2024-02-14 15:26 UTC, vkrashenko commented on client-app/pages/company/info.vue
> +                    class="flex items-center"
fixed

2024-02-15 04:13 UTC, goldenmaya approved these changes

2024-02-15 09:06 UTC, merged